# config.yml

# mdoel args
model_type:
  intrusion_detection
model:        
  input_dim: 193
  num_classes: 5
  device: cuda

# trainning args
traininng:
  batch_size: 64               
  epochs: 1000          
  learning_rate: 0.01  
  optimizer: Adam              
  weight_decay: 0.0
  clip_max_norm: 0.5
  factor: 0.3
  patience: 15         
  device: cuda


dataset_type:
  intrusion_detection
dataset:
  train_data_path: "data/train.jsonl"       
  test_data_path: "data/train.jsonl"       
  valid_data_path: "data/train.jsonl"       


logging:
  log_interval: 100             
  save_dir: "./saved_model/intrusion_detection"   
